services:
  postgres:

    networks:
      - populate_db

    container_name: airbnb-database
    image: postgres

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: airbnb

    ports:
      - "5433:5432"

  etl:
    build: .
    networks:
      - populate_db
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_started

networks:
  populate_db:
