CREATE SCHEMA IF NOT EXISTS dw;

DROP TABLE IF EXISTS dw.FATO_ANUNCIO;
DROP TABLE IF EXISTS dw.DIM_ANFITRIAO;
DROP TABLE IF EXISTS dw.DIM_LOCALIZACAO;
DROP TABLE IF EXISTS dw.DIM_PROPRIEDADE;
DROP TABLE IF EXISTS dw.DIM_ULTIMA_AVALIACAO;

CREATE TABLE dw.DIM_ANFITRIAO (
    SRK_anfi BIGSERIAL PRIMARY KEY,
    nm_anfi VARCHAR(255),
    anfi_verif BOOLEAN,
    anfi_tot_anun INTEGER
);

CREATE TABLE dw.DIM_LOCALIZACAO (
    SRK_local BIGSERIAL PRIMARY KEY,
    lat NUMERIC(10, 7),
    long NUMERIC(10, 7),
    bairro VARCHAR(255),
    grp_bairro VARCHAR(255)
);

CREATE TABLE dw.DIM_ULTIMA_AVALIACAO (
    SRK_aval BIGSERIAL PRIMARY KEY,
    dt_ult_rev DATE,
    ano INTEGER,
    mes INTEGER,
    trimestre INTEGER
);

CREATE TABLE dw.DIM_PROPRIEDADE (
    SRK_prop BIGSERIAL PRIMARY KEY,
    nm_anun TEXT,
    tipo_qto VARCHAR(100),
    min_noites INTEGER,
    pol_cancel VARCHAR(100),
    res_inst BOOLEAN,
    ano_constr INTEGER,
    tem_regras BOOLEAN
);

CREATE TABLE dw.FATO_ANUNCIO (
    SRK_fato_anuncio BIGSERIAL PRIMARY KEY,
    
    disp_365 INTEGER,
    preco NUMERIC(10, 2),
    tx_serv NUMERIC(10, 2),
    tot_rev INTEGER,
    rev_mes NUMERIC(5, 2),
    nota_rev NUMERIC(10, 2),
    
    SRK_anfi BIGINT NOT NULL,
    SRK_local BIGINT NOT NULL,
    SRK_aval BIGINT NOT NULL,
    SRK_prop BIGINT NOT NULL
);
 
ALTER TABLE dw.FATO_ANUNCIO ADD CONSTRAINT SRK_FATO_ANUNCIO_ANFI
    FOREIGN KEY (SRK_anfi)
    REFERENCES dw.DIM_ANFITRIAO (SRK_anfi)
    ON DELETE RESTRICT;
 
ALTER TABLE dw.FATO_ANUNCIO ADD CONSTRAINT SRK_FATO_ANUNCIO_LOCAL
    FOREIGN KEY (SRK_local)
    REFERENCES dw.DIM_LOCALIZACAO (SRK_local)
    ON DELETE RESTRICT;
 
ALTER TABLE dw.FATO_ANUNCIO ADD CONSTRAINT SRK_FATO_ANUNCIO_AVAL
    FOREIGN KEY (SRK_aval)
    REFERENCES dw.DIM_ULTIMA_AVALIACAO (SRK_aval)
    ON DELETE RESTRICT;
 
ALTER TABLE dw.FATO_ANUNCIO ADD CONSTRAINT SRK_FATO_ANUNCIO_PROP
    FOREIGN KEY (SRK_prop)
    REFERENCES dw.DIM_PROPRIEDADE (SRK_prop)
    ON DELETE RESTRICT;

ALTER TABLE dw.FATO_ANUNCIO ADD CONSTRAINT CHK_FATO_REV_MES_NOT_NAN CHECK (rev_mes IS NULL OR rev_mes::text !~* '^(nan|inf|-inf)$');
ALTER TABLE dw.FATO_ANUNCIO ADD CONSTRAINT CHK_FATO_PRECO_NOT_NAN   CHECK (preco IS NULL OR preco::text !~* '^(nan|inf|-inf)$');
ALTER TABLE dw.FATO_ANUNCIO ADD CONSTRAINT CHK_FATO_TXSERV_NOT_NAN  CHECK (tx_serv IS NULL OR tx_serv::text !~* '^(nan|inf|-inf)$');
ALTER TABLE dw.FATO_ANUNCIO ADD CONSTRAINT CHK_FATO_TOTREV_NOT_NAN  CHECK (tot_rev IS NULL OR tot_rev::text !~* '^(nan|inf|-inf)$');
ALTER TABLE dw.FATO_ANUNCIO ADD CONSTRAINT CHK_FATO_NOTAREV_NOT_NAN CHECK (nota_rev IS NULL OR nota_rev::text !~* '^(nan|inf|-inf)$');

CREATE INDEX IDX_FATO_FK_ANFI ON dw.FATO_ANUNCIO(SRK_anfi);
CREATE INDEX IDX_FATO_FK_LOCAL ON dw.FATO_ANUNCIO(SRK_local);
CREATE INDEX IDX_FATO_FK_AVAL ON dw.FATO_ANUNCIO(SRK_aval);
CREATE INDEX IDX_FATO_FK_PROP ON dw.FATO_ANUNCIO(SRK_prop);
