CREATE SCHEMA IF NOT EXISTS gold;

DROP TABLE IF EXISTS gold.FATO_ANUNCIO;
DROP TABLE IF EXISTS gold.DIM_ANFITRIAO;
DROP TABLE IF EXISTS gold.DIM_LOCALIZACAO;
DROP TABLE IF EXISTS gold.DIM_PROPRIEDADE;
DROP TABLE IF EXISTS gold.DIM_ULTIMA_AVALIACAO;

CREATE TABLE gold.DIM_ANFITRIAO (
    SRK_anfi BIGSERIAL PRIMARY KEY,
    nm_anfi VARCHAR(255),
    anfi_verif BOOLEAN,
    anfi_tot_anun INTEGER
);

CREATE TABLE gold.DIM_LOCALIZACAO (
    SRK_local BIGSERIAL PRIMARY KEY,
    lat NUMERIC(10, 7),
    long NUMERIC(10, 7),
    bairro VARCHAR(255),
    grp_bairro VARCHAR(255)
);

CREATE TABLE gold.DIM_ULTIMA_AVALIACAO (
    SRK_aval BIGSERIAL PRIMARY KEY,
    dt_ult_rev DATE,
    ano INTEGER,
    mes INTEGER,
    trimestre INTEGER
);

CREATE TABLE gold.DIM_PROPRIEDADE (
    SRK_prop BIGSERIAL PRIMARY KEY,
    nm_anun TEXT,
    tipo_qto VARCHAR(100),
    min_noites INTEGER,
    pol_cancel VARCHAR(100),
    res_inst BOOLEAN,
    ano_constr INTEGER,
    tem_regras BOOLEAN
);

CREATE TABLE gold.FATO_ANUNCIO (
    SRK_fato_anuncio BIGSERIAL PRIMARY KEY,
    
    disp_365 INTEGER,
    preco NUMERIC(10, 2),
    tx_serv NUMERIC(10, 2),
    tot_rev INTEGER,
    rev_mes NUMERIC(5, 2),
    nota_rev NUMERIC(10, 2),
    
    SRK_anfi BIGINT NOT NULL,
    SRK_local BIGINT NOT NULL,
    SRK_aval BIGINT NOT NULL,
    SRK_prop BIGINT NOT NULL
);
 
ALTER TABLE gold.FATO_ANUNCIO ADD CONSTRAINT SRK_FATO_ANUNCIO_ANFI
    FOREIGN KEY (SRK_anfi)
    REFERENCES gold.DIM_ANFITRIAO (SRK_anfi)
    ON DELETE RESTRICT;
 
ALTER TABLE gold.FATO_ANUNCIO ADD CONSTRAINT SRK_FATO_ANUNCIO_LOCAL
    FOREIGN KEY (SRK_local)
    REFERENCES gold.DIM_LOCALIZACAO (SRK_local)
    ON DELETE RESTRICT;
 
ALTER TABLE gold.FATO_ANUNCIO ADD CONSTRAINT SRK_FATO_ANUNCIO_AVAL
    FOREIGN KEY (SRK_aval)
    REFERENCES gold.DIM_ULTIMA_AVALIACAO (SRK_aval)
    ON DELETE RESTRICT;
 
ALTER TABLE gold.FATO_ANUNCIO ADD CONSTRAINT SRK_FATO_ANUNCIO_PROP
    FOREIGN KEY (SRK_prop)
    REFERENCES gold.DIM_PROPRIEDADE (SRK_prop)
    ON DELETE RESTRICT;

CREATE INDEX idx_fato_fk_anfi ON gold.FATO_ANUNCIO(SRK_anfi);
CREATE INDEX idx_fato_fk_local ON gold.FATO_ANUNCIO(SRK_local);
CREATE INDEX idx_fato_fk_aval ON gold.FATO_ANUNCIO(SRK_aval);
CREATE INDEX idx_fato_fk_prop ON gold.FATO_ANUNCIO(SRK_prop);